<a href="https://colab.research.google.com/github/rakhapodra13-ship-it/ambulancenavigation/blob/main/Salinan_dari_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# ==========================================
# INPUT NIM
# ==========================================
X = 5
Y = 6

print(f"Menggunakan nilai X = {X} dan Y = {Y}\n")
print("="*50)
print("BAGIAN 1: MATRIKS P dan Q (4x4)")
print("="*50)

# Inisialisasi Matriks P dan Q
P = np.array([
    [1, 2, X, -1],
    [3, 0, 1, 4],
    [-1, 2, 5, Y],
    [0, 1, -2, 3]
])

Q = np.array([
    [4, X, -1, 2],
    [1, 3, 0, 1],
    [2, -1, 2, Y],
    [0, 5, 1, -3]
])

# 1. P + Q
p1 = P + Q
print("1. P + Q :\n", p1, "\n")

# 2. 3P - 2Q
p2 = 3*P - 2*Q
print("2. 3P - 2Q :\n", p2, "\n")

# 3. P x Q
p3 = np.matmul(P, Q)
print("3. P x Q :\n", p3, "\n")

# 4. P x Q - Q x P
p4 = np.matmul(P, Q) - np.matmul(Q, P)
print("4. P x Q - Q x P :\n", p4, "\n")

# 5. (P + Q^T) x P
Q_T = Q.T
p5 = np.matmul(P + Q_T, P)
print("5. (P + Q^T) x P :\n", p5, "\n")


print("="*50)
print("BAGIAN 2: MATRIKS A dan B")
print("="*50)

# Inisialisasi Matriks A dan B
# Catatan: Pada soal bagian 2, x dan y huruf kecil
x = X
y = Y

A = np.array([
    [1, y, 3],
    [-2, 6, x]
])

B = np.array([
    [1, 2],
    [5, 7],
    [3, -x]
])

# 1. A - B^T
B_T = B.T
b1 = A - B_T
print("1. A - B^T :\n", b1, "\n")

# 2. AB
b2 = np.matmul(A, B)
print("2. AB :\n", b2, "\n")

# 3. BA
b3 = np.matmul(B, A)
print("3. BA :\n", b3, "\n")

# 4. A^T x B^T
A_T = A.T
b4 = np.matmul(A_T, B_T)
print("4. A^T x B^T :\n", b4, "\n")

# 5. (BA)^T
b5 = b3.T
print("5. (BA)^T :\n", b5, "\n")


Menggunakan nilai X = 5 dan Y = 6

BAGIAN 1: MATRIKS P dan Q (4x4)
1. P + Q :
 [[ 5  7  4  1]
 [ 4  3  1  5]
 [ 1  1  7 12]
 [ 0  6 -1  0]] 

2. 3P - 2Q :
 [[-5 -4 17 -7]
 [ 7 -6  3 10]
 [-7  8 11  6]
 [ 0 -7 -8 15]] 

3. P x Q :
 [[ 16   1   8  37]
 [ 14  34   3   0]
 [  8  26  17  12]
 [ -3  20  -1 -20]] 

4. P x Q - Q x P :
 [[ -4  -7  -8  21]
 [  4  31  -3 -14]
 [ 11  12  10 -12]
 [-17  21 -17 -37]] 

5. (P + Q^T) x P :
 [[ 7 23 65 46]
 [17 25 25 31]
 [-3 17 13 73]
 [ 4 12 32 30]] 

BAGIAN 2: MATRIKS A dan B
1. A - B^T :
 [[ 0  1  0]
 [-4 -1 10]] 

2. AB :
 [[40 29]
 [43 13]] 

3. BA :
 [[ -3  18  13]
 [ -9  72  50]
 [ 13 -12 -16]] 

4. A^T x B^T :
 [[ -3  -9  13]
 [ 18  72 -12]
 [ 13  50 -16]] 

5. (BA)^T :
 [[ -3  -9  13]
 [ 18  72 -12]
 [ 13  50 -16]] 

